### ISSUE TITLE
PorkyLib::Symmetric#client should rescue AWS configuration errors

### ISSUE THREAD

**Issue by bvrooman** [Zetatango/porky_lib#172]
If PorkyLib is configured improperly, such as with a blank region, key ID, or secret, the `aws-sdk-error` thrown by the `Seahorse::Client::Base` is propagated back to the caller application and causes execution to exit (unless rescued therein). When an error is encountered, PorkyLib should raise its own class of error.

We should consider rescuing:
- `Aws::Errors::MissingRegionError`
- `UnrecognizedClientException`
- `Aws::Errors::ServiceError`

This way, clients using PorkyLib, such as DaffyLib, don't need to rescue these errors, and can instead rescue a PorkyLib error.

**Comment by dragoszt** [comment]
I don't agree 😆 feel free to re-open if you think you feel strong about it
